# Generated by Django 4.0.6 on 2022-07-26 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.IntegerField()),
                ('usd_price', models.IntegerField()),
                ('delivery_date', models.DateField()),
                ('rub_price', models.IntegerField()),
            ],
        ),
    ]
