# Generated by Django 4.0.6 on 2022-07-26 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksfront', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sheetdata',
            old_name='delivery_date',
            new_name='delivery_time',
        ),
    ]
